<script type="text/javascript">

//<![CDATA[

var ARCHITOUCH = [
    {
        "inputparameters.parameter.0.default": "60",
        "inputparameters.parameter.0._name": "NetworkTimeout",
        "inputparameters.parameter.0._description": "Timeout for blocking network calls (in seconds).  Use -1 for no timeout.",
        "inputparameters.parameter.0._type": "S16",
        "inputparameters.parameter.1._name": "TargetIp",
        "inputparameters.parameter.1._description": "Target IP Address",
        "inputparameters.parameter.1._type": "IPv4",
        "inputparameters.parameter.2.default": "49152",
        "inputparameters.parameter.2._name": "TargetPort",
        "inputparameters.parameter.2._description": "Port used by a TCP RPC service",
        "inputparameters.parameter.2._type": "TcpPort",
        "outputparameters.parameter._name": "TargetOsArchitecture",
        "outputparameters.parameter._description": "Target architecture",
        "outputparameters.parameter._type": "String",
        "errors.errorcode._name": "ARTO_NETWORK_ERROR",
        "errors.errorcode._value": "65",
        "errors.errorcode._description": "A network error occured",
        "redirection.local._protocol": "TCP",
        "redirection.local._listenaddr": "TargetIp",
        "redirection.local._listenport": "TargetPort",
        "redirection.local._destaddr": "TargetIp",
        "redirection.local._destport": "TargetPort",
        "redirection.local._closeoncompletion": "true",
        "logic": "",
        "_xmlns": "urn:trch",
        "_id": "5f75119c8cc493e28286b5315d05d79bfc50b039",
        "_name": "Architouch",
        "_version": "1.0.0",
        "_configversion": "1.0.0.0",
        "_schemaversion": "2.0.0"
    }
]

var DOMAINTOUCH = [
    {
        "inputparameters.parameter.0._name": "NetworkTimeout",
        "inputparameters.parameter.0._description": "Timeout for blocking network calls (in seconds)",
        "inputparameters.parameter.0._type": "S16",
        "inputparameters.parameter.0._default": "60",
        "inputparameters.parameter.0.__prefix": "BADTOUCH",
        "inputparameters.parameter.1._name": "TargetIp",
        "inputparameters.parameter.1._description": "Domain Controller's IP address",
        "inputparameters.parameter.1._type": "IPv4",
        "inputparameters.parameter.1._binding": "//identifier",
        "inputparameters.parameter.1.__prefix": "BADTOUCH",
        "inputparameters.parameter.2._name": "TargetPort",
        "inputparameters.parameter.2._description": "Port used by the netlogon service",
        "inputparameters.parameter.2._type": "TcpPort",
        "inputparameters.parameter.2._binding": "//service[name='smb']/port",
        "inputparameters.parameter.2._default": "445",
        "inputparameters.parameter.2.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.paramgroup.0.parameter.0._name": "Username",
        "inputparameters.paramchoice.paramgroup.0.parameter.0._description": "Username entered as hex bytes (in Unicode)",
        "inputparameters.paramchoice.paramgroup.0.parameter.0._type": "UString",
        "inputparameters.paramchoice.paramgroup.0.parameter.0.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.paramgroup.0.parameter.1._name": "Credential",
        "inputparameters.paramchoice.paramgroup.0.parameter.1._description": "Unicode password entered as hex bytes (in Unicode)",
        "inputparameters.paramchoice.paramgroup.0.parameter.1._type": "UString",
        "inputparameters.paramchoice.paramgroup.0.parameter.1.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.paramgroup.0._name": "UnicodeCreds",
        "inputparameters.paramchoice.paramgroup.0._description": "Unicode encoded credentials",
        "inputparameters.paramchoice.paramgroup.0.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.paramgroup.1.parameter.0._name": "Username",
        "inputparameters.paramchoice.paramgroup.1.parameter.0._description": "Machine name, including the '$' character, in UNICODE",
        "inputparameters.paramchoice.paramgroup.1.parameter.0._type": "UString",
        "inputparameters.paramchoice.paramgroup.1.parameter.0.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.paramgroup.1.parameter.1._name": "Credential",
        "inputparameters.paramchoice.paramgroup.1.parameter.1._description": "Hash of machine password entered as HEX BYTES.  This can be obtained from lsadump",
        "inputparameters.paramchoice.paramgroup.1.parameter.1._type": "UString",
        "inputparameters.paramchoice.paramgroup.1.parameter.1.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.paramgroup.1._name": "MachineHash",
        "inputparameters.paramchoice.paramgroup.1._description": "Machine credentials, obtained from LSADump",
        "inputparameters.paramchoice.paramgroup.1.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.paramgroup.2.parameter.0._name": "Username",
        "inputparameters.paramchoice.paramgroup.2.parameter.0._description": "Username in Unicode",
        "inputparameters.paramchoice.paramgroup.2.parameter.0._type": "UString",
        "inputparameters.paramchoice.paramgroup.2.parameter.0.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.paramgroup.2.parameter.1._name": "Credential",
        "inputparameters.paramchoice.paramgroup.2.parameter.1._description": "User password entered as HEX BYTES. This can be obtained from lsadump",
        "inputparameters.paramchoice.paramgroup.2.parameter.1._type": "UString",
        "inputparameters.paramchoice.paramgroup.2.parameter.1.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.paramgroup.2._name": "PasswordHash",
        "inputparameters.paramchoice.paramgroup.2._description": "Password hash",
        "inputparameters.paramchoice.paramgroup.2.__prefix": "BADTOUCH",
        "inputparameters.paramchoice._name": "CredentialType",
        "inputparameters.paramchoice._description": "Password, password hash, ticket, etc",
        "inputparameters.paramchoice._default": "Ticket",
        "inputparameters.paramchoice.__prefix": "BADTOUCH",
        "inputparameters.__prefix": "BADTOUCH",
        "outputparameters.parameter.0._name": "CredentialType",
        "outputparameters.parameter.0._description": "CredentialType used by this plugin",
        "outputparameters.parameter.0._type": "String",
        "outputparameters.parameter.0.__prefix": "BADTOUCH",
        "outputparameters.parameter.1._name": "Username",
        "outputparameters.parameter.1._description": "Username used by this plugin",
        "outputparameters.parameter.1._type": "UString",
        "outputparameters.parameter.1.__prefix": "BADTOUCH",
        "outputparameters.parameter.2._name": "Credential",
        "outputparameters.parameter.2._description": "Credential used by this plugin",
        "outputparameters.parameter.2._type": "UString",
        "outputparameters.parameter.2.__prefix": "BADTOUCH",
        "outputparameters.parameter.3._name": "DomainNetbios",
        "outputparameters.parameter.3._description": "Target domain NetBIOS name (in Unicode)",
        "outputparameters.parameter.3._type": "UString",
        "outputparameters.parameter.3.__prefix": "BADTOUCH",
        "outputparameters.parameter.4._name": "DomainDns",
        "outputparameters.parameter.4._description": "Target domain DNS name (in Unicode)",
        "outputparameters.parameter.4._type": "UString",
        "outputparameters.parameter.4.__prefix": "BADTOUCH",
        "outputparameters.parameter.5._name": "DomainSid",
        "outputparameters.parameter.5._description": "Target domain SID",
        "outputparameters.parameter.5._type": "String",
        "outputparameters.parameter.5.__prefix": "BADTOUCH",
        "outputparameters.parameter.6._name": "DomainGuid",
        "outputparameters.parameter.6._description": "Target domain GUID",
        "outputparameters.parameter.6._type": "String",
        "outputparameters.parameter.6.__prefix": "BADTOUCH",
        "outputparameters.__prefix": "BADTOUCH",
        "redirection.local._protocol": "TCP",
        "redirection.local._listenaddr": "TargetIp",
        "redirection.local._listenport": "TargetPort",
        "redirection.local._destaddr": "//identifier",
        "redirection.local._destport": "//service[name='smb']/port",
        "redirection.local._closeoncompletion": "true",
        "redirection.local.__prefix": "BADTOUCH",
        "redirection.__prefix": "BADTOUCH",
        "logic.or.os.0._family": "windows",
        "logic.or.os.0._name": "Windows 2000",
        "logic.or.os.0.__prefix": "BADTOUCH",
        "logic.or.os.1._family": "windows",
        "logic.or.os.1._name": "Windows XP",
        "logic.or.os.1.__prefix": "BADTOUCH",
        "logic.or.os.2._family": "windows",
        "logic.or.os.2._name": "Windows 2003",
        "logic.or.os.2.__prefix": "BADTOUCH",
        "logic.or.os.3._family": "windows",
        "logic.or.os.3._name": "Windows 2003 R2",
        "logic.or.os.3.__prefix": "BADTOUCH",
        "logic.or.os.4._family": "windows",
        "logic.or.os.4._name": "Windows Vista",
        "logic.or.os.4.__prefix": "BADTOUCH",
        "logic.or.os.5._family": "windows",
        "logic.or.os.5._name": "Windows 2008",
        "logic.or.os.5.__prefix": "BADTOUCH",
        "logic.or.os.6._family": "windows",
        "logic.or.os.6._name": "Windows 7",
        "logic.or.os.6.__prefix": "BADTOUCH",
        "logic.or.os.7._family": "windows",
        "logic.or.os.7._name": "Windows 2008 R2",
        "logic.or.os.7.__prefix": "BADTOUCH",
        "logic.or.__prefix": "BADTOUCH",
        "logic.__prefix": "BADTOUCH",
        "_xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
        "_xmlns:t": "tc0",
        "_id": "19e475ba095c90e14ea158179b5b284d6e63bba3",
        "_name": "Domaintouch",
        "_version": "1.1.1",
        "_configversion": "1.1.1.0",
        "__prefix": "BADTOUCH"
    }
]

var ECLIPSEDWINGTOUCH = [
    {
        "inputparameters.parameter.0._name": "TargetIp",
        "inputparameters.parameter.0._description": "Target IP Address",
        "inputparameters.parameter.0._type": "IPv4",
        "inputparameters.parameter.0._binding": "//identifier",
        "inputparameters.parameter.0.__prefix": "BADTOUCH",
        "inputparameters.parameter.1._name": "TargetPort",
        "inputparameters.parameter.1._description": "Port used by SMB or NBT",
        "inputparameters.parameter.1._type": "TcpPort",
        "inputparameters.parameter.1.__prefix": "BADTOUCH",
        "inputparameters.parameter.2._name": "ServerName",
        "inputparameters.parameter.2._description": "Server Name",
        "inputparameters.parameter.2._type": "String",
        "inputparameters.parameter.2._value": "*SMBSERVER",
        "inputparameters.parameter.2._hidden": "true",
        "inputparameters.parameter.2.__prefix": "BADTOUCH",
        "inputparameters.parameter.3._name": "ClientName",
        "inputparameters.parameter.3._description": "Client Name",
        "inputparameters.parameter.3._type": "String",
        "inputparameters.parameter.3._value": "*SMBCLIENT",
        "inputparameters.parameter.3._hidden": "true",
        "inputparameters.parameter.3.__prefix": "BADTOUCH",
        "inputparameters.parameter.4._name": "NetworkTimeout",
        "inputparameters.parameter.4._description": "Timeout for blocking network calls (in seconds).  Use -1 for no timeout.",
        "inputparameters.parameter.4._type": "S16",
        "inputparameters.parameter.4._default": "60",
        "inputparameters.parameter.4.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.paramgroup.0._name": "SMB",
        "inputparameters.paramchoice.paramgroup.0._description": "SMB over TCP (port 445)",
        "inputparameters.paramchoice.paramgroup.0.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.paramgroup.1._name": "NBT",
        "inputparameters.paramchoice.paramgroup.1._description": "Netbios over TCP (port 139)",
        "inputparameters.paramchoice.paramgroup.1.__prefix": "BADTOUCH",
        "inputparameters.paramchoice._name": "Protocol",
        "inputparameters.paramchoice._description": "Protocol to connect to target with",
        "inputparameters.paramchoice.__prefix": "BADTOUCH",
        "inputparameters.__prefix": "BADTOUCH",
        "outputparameters.parameter.0._name": "Contract",
        "outputparameters.parameter.0._description": "The contract fulfilled by this plugin",
        "outputparameters.parameter.0._type": "String",
        "outputparameters.parameter.0._value": "VulnScan",
        "outputparameters.parameter.0.__prefix": "BADTOUCH",
        "outputparameters.parameter.1._name": "OsPatch",
        "outputparameters.parameter.1._description": "",
        "outputparameters.parameter.1._type": "String",
        "outputparameters.parameter.1._required": "false",
        "outputparameters.parameter.1.__prefix": "BADTOUCH",
        "outputparameters.__prefix": "BADTOUCH",
        "redirection.local._protocol": "TCP",
        "redirection.local._listenaddr": "TargetIp",
        "redirection.local._listenport": "TargetPort",
        "redirection.local._destaddr": "//identifier",
        "redirection.local._destport": "TargetPort",
        "redirection.local._closeoncompletion": "true",
        "redirection.local.__prefix": "BADTOUCH",
        "redirection.__prefix": "BADTOUCH",
        "logic.or.service.0.bindtovalue._name": "Protocol",
        "logic.or.service.0.bindtovalue._value": "SMB",
        "logic.or.service.0.bindtovalue.__prefix": "BADTOUCH",
        "logic.or.service.0.bindtopath._name": "TargetPort",
        "logic.or.service.0.bindtopath._path": "//service[name='smb']/port",
        "logic.or.service.0.bindtopath.__prefix": "BADTOUCH",
        "logic.or.service.0._name": "smb",
        "logic.or.service.0.__prefix": "BADTOUCH",
        "logic.or.service.1.bindtovalue._name": "Protocol",
        "logic.or.service.1.bindtovalue._value": "NBT",
        "logic.or.service.1.bindtovalue.__prefix": "BADTOUCH",
        "logic.or.service.1.bindtopath._name": "TargetPort",
        "logic.or.service.1.bindtopath._path": "//service[name='nbt']/port",
        "logic.or.service.1.bindtopath.__prefix": "BADTOUCH",
        "logic.or.service.1._name": "nbt",
        "logic.or.service.1.__prefix": "BADTOUCH",
        "logic.or.__prefix": "BADTOUCH",
        "logic.__prefix": "BADTOUCH",
        "_xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
        "_xmlns:t": "tc0",
        "_id": "04b6895e13883c32fe5575de1e666145cf149b7f",
        "_name": "Eclipsedwingtouch",
        "_version": "1.0.4",
        "_configversion": "1.0.4.0",
        "__prefix": "BADTOUCH"
    }
]

var EDUCATEDSCHOLARTOUCH = [
    {
        "inputparameters.parameter.0._name": "TargetIp",
        "inputparameters.parameter.0._description": "Target IP Address",
        "inputparameters.parameter.0._type": "IPv4",
        "inputparameters.parameter.0._binding": "//identifier",
        "inputparameters.parameter.0.__prefix": "BADTOUCH",
        "inputparameters.parameter.1._name": "TargetPort",
        "inputparameters.parameter.1._description": "Port used by SMB",
        "inputparameters.parameter.1._type": "TcpPort",
        "inputparameters.parameter.1._binding": "//service[name='smb']/port",
        "inputparameters.parameter.1.__prefix": "BADTOUCH",
        "inputparameters.parameter.2._name": "NetworkTimeout",
        "inputparameters.parameter.2._description": "Timeout for blocking network calls (in seconds).  Use -1 for no timeout.",
        "inputparameters.parameter.2._type": "S16",
        "inputparameters.parameter.2._default": "60",
        "inputparameters.parameter.2.__prefix": "BADTOUCH",
        "inputparameters.parameter.3._name": "ProcessIDHigh",
        "inputparameters.parameter.3._description": "",
        "inputparameters.parameter.3._type": "U16",
        "inputparameters.parameter.3._value": "0x03F",
        "inputparameters.parameter.3._hidden": "true",
        "inputparameters.parameter.3.__prefix": "BADTOUCH",
        "inputparameters.__prefix": "BADTOUCH",
        "outputparameters.parameter._name": "Contract",
        "outputparameters.parameter._description": "The contract fulfilled by this plugin",
        "outputparameters.parameter._type": "String",
        "outputparameters.parameter._value": "Touch",
        "outputparameters.parameter.__prefix": "BADTOUCH",
        "outputparameters.__prefix": "BADTOUCH",
        "redirection.local._protocol": "TCP",
        "redirection.local._listenaddr": "TargetIp",
        "redirection.local._listenport": "TargetPort",
        "redirection.local._destaddr": "//identifier",
        "redirection.local._destport": "//service[name='smb']/port",
        "redirection.local._closeoncompletion": "true",
        "redirection.local.__prefix": "BADTOUCH",
        "redirection.__prefix": "BADTOUCH",
        "_xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
        "_xmlns:t": "tc0",
        "_id": "d0178d92d73ae8348f7ca99bf78c110e8ba8bf1d",
        "_name": "Educatedscholartouch",
        "_version": "1.0.0",
        "_configversion": "1.0.0.0",
        "__prefix": "BADTOUCH"
    }
]

var EMERALDTHREADTOUCH = [
    {
        "inputparameters.parameter.0._name": "NetworkTimeout",
        "inputparameters.parameter.0._description": "Timeout for blocking network calls (in seconds).  Use -1 for no timeout.",
        "inputparameters.parameter.0._type": "S16",
        "inputparameters.parameter.0._default": "60",
        "inputparameters.parameter.0.__prefix": "BADTOUCH",
        "inputparameters.parameter.1._name": "TargetIp",
        "inputparameters.parameter.1._description": "Target IP Address",
        "inputparameters.parameter.1._type": "IPv4",
        "inputparameters.parameter.1._binding": "//identifier",
        "inputparameters.parameter.1.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.0.paramgroup.0.parameter._name": "TargetPort",
        "inputparameters.paramchoice.0.paramgroup.0.parameter._description": "Port used by SMB",
        "inputparameters.paramchoice.0.paramgroup.0.parameter._type": "TcpPort",
        "inputparameters.paramchoice.0.paramgroup.0.parameter._default": "445",
        "inputparameters.paramchoice.0.paramgroup.0.parameter.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.0.paramgroup.0._name": "SMB",
        "inputparameters.paramchoice.0.paramgroup.0._description": "SMB over TCP",
        "inputparameters.paramchoice.0.paramgroup.0.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.0.paramgroup.1.parameter._name": "TargetPort",
        "inputparameters.paramchoice.0.paramgroup.1.parameter._description": "Port used by Netbios",
        "inputparameters.paramchoice.0.paramgroup.1.parameter._type": "TcpPort",
        "inputparameters.paramchoice.0.paramgroup.1.parameter._default": "139",
        "inputparameters.paramchoice.0.paramgroup.1.parameter.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.0.paramgroup.1._name": "NBT",
        "inputparameters.paramchoice.0.paramgroup.1._description": "Netbios over TCP",
        "inputparameters.paramchoice.0.paramgroup.1.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.0._name": "Protocol",
        "inputparameters.paramchoice.0._description": "Protocol to connect to target with",
        "inputparameters.paramchoice.0._default": "SMB",
        "inputparameters.paramchoice.0.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.0._name": "Anonymous",
        "inputparameters.paramchoice.1.paramgroup.0._description": "Anonymous (NULL session)",
        "inputparameters.paramchoice.1.paramgroup.0.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.1._name": "Guest",
        "inputparameters.paramchoice.1.paramgroup.1._description": "Guest account",
        "inputparameters.paramchoice.1.paramgroup.1.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.2.parameter._name": "Username",
        "inputparameters.paramchoice.1.paramgroup.2.parameter._description": "",
        "inputparameters.paramchoice.1.paramgroup.2.parameter._type": "UString",
        "inputparameters.paramchoice.1.paramgroup.2.parameter.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.2._name": "No password",
        "inputparameters.paramchoice.1.paramgroup.2._description": "User account with no password set",
        "inputparameters.paramchoice.1.paramgroup.2.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.3.parameter.0._name": "Username",
        "inputparameters.paramchoice.1.paramgroup.3.parameter.0._description": "",
        "inputparameters.paramchoice.1.paramgroup.3.parameter.0._type": "UString",
        "inputparameters.paramchoice.1.paramgroup.3.parameter.0.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.3.parameter.1._name": "Password",
        "inputparameters.paramchoice.1.paramgroup.3.parameter.1._description": "",
        "inputparameters.paramchoice.1.paramgroup.3.parameter.1._type": "UString",
        "inputparameters.paramchoice.1.paramgroup.3.parameter.1.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.3._name": "Password",
        "inputparameters.paramchoice.1.paramgroup.3._description": "Username and password",
        "inputparameters.paramchoice.1.paramgroup.3.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.4.parameter.0._name": "Username",
        "inputparameters.paramchoice.1.paramgroup.4.parameter.0._description": "",
        "inputparameters.paramchoice.1.paramgroup.4.parameter.0._type": "UString",
        "inputparameters.paramchoice.1.paramgroup.4.parameter.0.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.4.parameter.1._name": "NTLMHash",
        "inputparameters.paramchoice.1.paramgroup.4.parameter.1._description": "NTLM password hash (in hex)",
        "inputparameters.paramchoice.1.paramgroup.4.parameter.1._type": "UString",
        "inputparameters.paramchoice.1.paramgroup.4.parameter.1.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.4._name": "NTLM hash",
        "inputparameters.paramchoice.1.paramgroup.4._description": "Username and NTLM hash",
        "inputparameters.paramchoice.1.paramgroup.4.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.0._name": "Username",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.0._description": "",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.0._type": "UString",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.0.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.1._name": "NTLMHash",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.1._description": "NTLM password hash (in hex)",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.1._type": "UString",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.1.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.2._name": "LANMANHash",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.2._description": "LANMAN password hash (in hex)",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.2._type": "UString",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.2.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.5._name": "Both hashes",
        "inputparameters.paramchoice.1.paramgroup.5._description": "Username, NTLM hash, and LANMAN hash",
        "inputparameters.paramchoice.1.paramgroup.5.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1._name": "Credentials",
        "inputparameters.paramchoice.1._description": "Type of credentials to use",
        "inputparameters.paramchoice.1.__prefix": "BADTOUCH",
        "inputparameters.__prefix": "BADTOUCH",
        "outputparameters.parameter._name": "PrinterName",
        "outputparameters.parameter._description": "The name of the printer on target",
        "outputparameters.parameter._type": "UString",
        "outputparameters.parameter._format": "List",
        "outputparameters.parameter.__prefix": "BADTOUCH",
        "outputparameters.__prefix": "BADTOUCH",
        "redirection.local._protocol": "TCP",
        "redirection.local._listenaddr": "TargetIp",
        "redirection.local._listenport": "TargetPort",
        "redirection.local._destaddr": "//identifier",
        "redirection.local._destport": "TargetPort",
        "redirection.local._closeoncompletion": "true",
        "redirection.local.__prefix": "BADTOUCH",
        "redirection.__prefix": "BADTOUCH",
        "logic.or.service.0.bindtovalue._name": "Protocol",
        "logic.or.service.0.bindtovalue._value": "SMB",
        "logic.or.service.0.bindtovalue.__prefix": "BADTOUCH",
        "logic.or.service.0.bindtopath._name": "TargetPort",
        "logic.or.service.0.bindtopath._path": "//service[name='smb']/port",
        "logic.or.service.0.bindtopath.__prefix": "BADTOUCH",
        "logic.or.service.0._name": "smb",
        "logic.or.service.0.__prefix": "BADTOUCH",
        "logic.or.service.1.bindtovalue._name": "Protocol",
        "logic.or.service.1.bindtovalue._value": "NBT",
        "logic.or.service.1.bindtovalue.__prefix": "BADTOUCH",
        "logic.or.service.1.bindtopath._name": "TargetPort",
        "logic.or.service.1.bindtopath._path": "//service[name='nbt']/port",
        "logic.or.service.1.bindtopath.__prefix": "BADTOUCH",
        "logic.or.service.1._name": "nbt",
        "logic.or.service.1.__prefix": "BADTOUCH",
        "logic.or.__prefix": "BADTOUCH",
        "logic.__prefix": "BADTOUCH",
        "_xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
        "_xmlns:t": "tc0",
        "_id": "cd337b30526a5e80bd5776b9479b117671ce2445",
        "_name": "Emeraldthreadtouch",
        "_version": "1.0.0",
        "_configversion": "1.0.0.0",
        "__prefix": "BADTOUCH"
    }
]

var ERRATICGOPHERTOUCH = [
    {
        "inputparameters.parameter.0._name": "TargetIp",
        "inputparameters.parameter.0._description": "Target IP Address",
        "inputparameters.parameter.0._type": "IPv4",
        "inputparameters.parameter.0._binding": "//identifier",
        "inputparameters.parameter.0.__prefix": "BADTOUCH",
        "inputparameters.parameter.1._name": "TargetPort",
        "inputparameters.parameter.1._description": "Port used by the MSRPC service. Typically 445 (SMB), 139 not available for ERGO",
        "inputparameters.parameter.1._type": "TcpPort",
        "inputparameters.parameter.1._default": "445",
        "inputparameters.parameter.1._binding": "//service[name='msrpc']/port",
        "inputparameters.parameter.1.__prefix": "BADTOUCH",
        "inputparameters.__prefix": "BADTOUCH",
        "outputparameters.parameter.0._name": "DimsvcEnabled",
        "outputparameters.parameter.0._type": "Boolean",
        "outputparameters.parameter.0._description": "",
        "outputparameters.parameter.0.__prefix": "BADTOUCH",
        "outputparameters.parameter.1._name": "Contract",
        "outputparameters.parameter.1._description": "The contract fulfilled by this plugin",
        "outputparameters.parameter.1._type": "String",
        "outputparameters.parameter.1._value": "Touch",
        "outputparameters.parameter.1.__prefix": "BADTOUCH",
        "outputparameters.__prefix": "BADTOUCH",
        "redirection.local._protocol": "TCP",
        "redirection.local._listenaddr": "TargetIp",
        "redirection.local._listenport": "TargetPort",
        "redirection.local._destaddr": "//identifier",
        "redirection.local._destport": "//service[name='msrpc']/port",
        "redirection.local._closeoncompletion": "true",
        "redirection.local.__prefix": "BADTOUCH",
        "redirection.__prefix": "BADTOUCH",
        "_xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
        "_xmlns:t": "tc0",
        "_id": "36d1ffadd2b385b2a8a5498a6e05825e8ab97825",
        "_name": "Erraticgophertouch",
        "_version": "1.0.1",
        "_configversion": "1.0.1.0",
        "__prefix": "BADTOUCH"
    }
]

var ESTEEMAUDITTOUCH = [
    {
        "inputparameters.parameter.0._type": "IPv4",
        "inputparameters.parameter.0._name": "TargetIp",
        "inputparameters.parameter.0._description": "Target IP Address",
        "inputparameters.parameter.1.default": "3389",
        "inputparameters.parameter.1._type": "TcpPort",
        "inputparameters.parameter.1._name": "TargetPort",
        "inputparameters.parameter.1._description": "Port used by the RDP service",
        "inputparameters.parameter.2.default": "60",
        "inputparameters.parameter.2._type": "S16",
        "inputparameters.parameter.2._name": "NetworkTimeout",
        "inputparameters.parameter.2._description": "Timeout for blocking network calls (in seconds).  Use -1 for no timeout.",
        "inputparameters.parameter.3.default": "10",
        "inputparameters.parameter.3._type": "S16",
        "inputparameters.parameter.3._name": "PacketTimeout",
        "inputparameters.parameter.3._description": "Timeout for each RDP packet.",
        "inputparameters.parameter.4.default": "300",
        "inputparameters.parameter.4._type": "U32",
        "inputparameters.parameter.4._name": "MaxProcessCount",
        "inputparameters.parameter.4._description": "The maximum number of RDP process loops to allow",
        "inputparameters.parameter.5.default": "false",
        "inputparameters.parameter.5._hidden": "true",
        "inputparameters.parameter.5._type": "Boolean",
        "inputparameters.parameter.5._name": "SendSpacebar",
        "inputparameters.parameter.5._description": "Whether to send spacebar to clear legal text caption or not",
        "inputparameters.parameter.6.default": "3",
        "inputparameters.parameter.6._hidden": "true",
        "inputparameters.parameter.6._type": "U32",
        "inputparameters.parameter.6._name": "ProcessCountToSendSpaceOn",
        "inputparameters.parameter.6._description": "Process loop to clear the legal text caption on",
        "inputparameters.parameter.7.default": "3",
        "inputparameters.parameter.7._hidden": "true",
        "inputparameters.parameter.7._type": "U32",
        "inputparameters.parameter.7._name": "MaxRDPLibErrorCount",
        "inputparameters.parameter.7._description": "Maximum number of RDPLib errors to allow",
        "outputparameters.parameter.0._type": "String",
        "outputparameters.parameter.0._name": "Architecture",
        "outputparameters.parameter.0._description": "Type of processor the target is running on",
        "outputparameters.parameter.1._type": "String",
        "outputparameters.parameter.1._name": "Target",
        "outputparameters.parameter.1._description": "Operating system and service pack of the target",
        "outputparameters.parameter.2._type": "String",
        "outputparameters.parameter.2._name": "EncryptionMethod",
        "outputparameters.parameter.2._description": "Encryption method the target is running",
        "outputparameters.parameter.3._type": "Boolean",
        "outputparameters.parameter.3._name": "SmartCardAuth",
        "outputparameters.parameter.3._description": "If the target supports smart card authentication",
        "outputparameters.parameter.4._type": "U32",
        "outputparameters.parameter.4._name": "RdpLibHertz",
        "outputparameters.parameter.4._description": "Extrapolated RdpLib processing cycles per second.",
        "outputparameters.parameter.5._type": "String",
        "outputparameters.parameter.5._name": "Contract",
        "outputparameters.parameter.5._description": "The contract fulfilled by this plugin",
        "redirection.local._protocol": "TCP",
        "redirection.local._listenaddr": "TargetIp",
        "redirection.local._listenport": "TargetPort",
        "redirection.local._closeoncompletion": "true",
        "redirection.local._destaddr": "TargetIp",
        "redirection.local._destport": "TargetPort",
        "_xmlns": "urn:trch",
        "_name": "Esteemaudittouch",
        "_version": "2.1.0",
        "_schemaversion": "2.1.0",
        "_configversion": "2.1.0.0",
        "_id": "d685b3979e2b52bd60cb34c4c0f91b522fa28f54"
    }
]

var EXPLODINGCANTOUCH = [
    {
        "inputparameters.parameter.0._name": "hostString",
        "inputparameters.parameter.0._description": "String to use in HTTP request",
        "inputparameters.parameter.0._type": "String",
        "inputparameters.parameter.0._default": "localhost",
        "inputparameters.parameter.0.__prefix": "BADTOUCH",
        "inputparameters.parameter.1._name": "maxSizeToCheck",
        "inputparameters.parameter.1._description": "Use 130 to ensure path size determination, less to send fewer requests.  70 will cover all exploitable sizes.",
        "inputparameters.parameter.1._type": "U32",
        "inputparameters.parameter.1._default": "70",
        "inputparameters.parameter.1.__prefix": "BADTOUCH",
        "inputparameters.parameter.2._name": "NetworkTimeout",
        "inputparameters.parameter.2._description": "Timeout for blocking network calls (in seconds).  Use -1 for no timeout.",
        "inputparameters.parameter.2._type": "S16",
        "inputparameters.parameter.2._default": "60",
        "inputparameters.parameter.2.__prefix": "BADTOUCH",
        "inputparameters.parameter.3._name": "EnableSSL",
        "inputparameters.parameter.3._description": "Enable SSL for HTTPS targets",
        "inputparameters.parameter.3._type": "Boolean",
        "inputparameters.parameter.3._default": "false",
        "inputparameters.parameter.3.__prefix": "BADTOUCH",
        "inputparameters.parameter.4._name": "TargetIp",
        "inputparameters.parameter.4._description": "Target IP Address",
        "inputparameters.parameter.4._type": "IPv4",
        "inputparameters.parameter.4._binding": "//identifier",
        "inputparameters.parameter.4.__prefix": "BADTOUCH",
        "inputparameters.parameter.5._name": "TargetPort",
        "inputparameters.parameter.5._description": "Port used by the HTTP service",
        "inputparameters.parameter.5._type": "TcpPort",
        "inputparameters.parameter.5.__prefix": "BADTOUCH",
        "inputparameters.parameter.6._name": "Delay",
        "inputparameters.parameter.6._description": "Number of seconds to wait between each request",
        "inputparameters.parameter.6._type": "U32",
        "inputparameters.parameter.6._default": "0",
        "inputparameters.parameter.6.__prefix": "BADTOUCH",
        "inputparameters.__prefix": "BADTOUCH",
        "outputparameters.parameter.0._name": "IISPathSize",
        "outputparameters.parameter.0._description": "Length of IIS path",
        "outputparameters.parameter.0._type": "U32",
        "outputparameters.parameter.0.__prefix": "BADTOUCH",
        "outputparameters.parameter.1._name": "hostString",
        "outputparameters.parameter.1._description": "String to use in HTTP requests",
        "outputparameters.parameter.1._type": "String",
        "outputparameters.parameter.1.__prefix": "BADTOUCH",
        "outputparameters.__prefix": "BADTOUCH",
        "redirection.local._protocol": "TCP",
        "redirection.local._listenaddr": "TargetIp",
        "redirection.local._listenport": "TargetPort",
        "redirection.local._destaddr": "//identifier",
        "redirection.local._destport": "TargetPort",
        "redirection.local._closeoncompletion": "true",
        "redirection.local.__prefix": "BADTOUCH",
        "redirection.__prefix": "BADTOUCH",
        "logic.or.service.0.and.product._name": "Microsoft IIS",
        "logic.or.service.0.and.product._version": "6.0",
        "logic.or.service.0.and.product.__prefix": "BADTOUCH",
        "logic.or.service.0.and.service.bindtovalue._name": "EnableSSL",
        "logic.or.service.0.and.service.bindtovalue._value": "false",
        "logic.or.service.0.and.service.bindtovalue.__prefix": "BADTOUCH",
        "logic.or.service.0.and.service.bindtopath._name": "TargetPort",
        "logic.or.service.0.and.service.bindtopath._path": "//service[name='http']/port",
        "logic.or.service.0.and.service.bindtopath.__prefix": "BADTOUCH",
        "logic.or.service.0.and.service._name": "http-option-propfind",
        "logic.or.service.0.and.service.__prefix": "BADTOUCH",
        "logic.or.service.0.and.__prefix": "BADTOUCH",
        "logic.or.service.0._name": "http",
        "logic.or.service.0.__prefix": "BADTOUCH",
        "logic.or.service.1.and.product._name": "Microsoft IIS",
        "logic.or.service.1.and.product._version": "6.0",
        "logic.or.service.1.and.product.__prefix": "BADTOUCH",
        "logic.or.service.1.and.service.bindtovalue._name": "EnableSSL",
        "logic.or.service.1.and.service.bindtovalue._value": "true",
        "logic.or.service.1.and.service.bindtovalue.__prefix": "BADTOUCH",
        "logic.or.service.1.and.service.bindtopath._name": "TargetPort",
        "logic.or.service.1.and.service.bindtopath._path": "//service[name='https']/port",
        "logic.or.service.1.and.service.bindtopath.__prefix": "BADTOUCH",
        "logic.or.service.1.and.service._name": "http-option-propfind",
        "logic.or.service.1.and.service.__prefix": "BADTOUCH",
        "logic.or.service.1.and.__prefix": "BADTOUCH",
        "logic.or.service.1._name": "https",
        "logic.or.service.1.__prefix": "BADTOUCH",
        "logic.or.__prefix": "BADTOUCH",
        "logic.__prefix": "BADTOUCH",
        "_xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
        "_xmlns:t": "tc0",
        "_id": "8f04b3348956b0ac62326e735eb33fae9106ff43",
        "_name": "Explodingcantouch",
        "_version": "1.2.1",
        "_configversion": "1.2.1.0",
        "__prefix": "BADTOUCH"
    }
]

var IISTOUCH = [
    {
        "inputparameters.parameter.0._name": "TargetIp",
        "inputparameters.parameter.0._description": "Target IP Address",
        "inputparameters.parameter.0._type": "IPv4",
        "inputparameters.parameter.0._binding": "//identifier",
        "inputparameters.parameter.0.__prefix": "BADTOUCH",
        "inputparameters.parameter.1._name": "TargetPort",
        "inputparameters.parameter.1._description": "Port used by the HTTP service",
        "inputparameters.parameter.1._type": "TcpPort",
        "inputparameters.parameter.1.__prefix": "BADTOUCH",
        "inputparameters.parameter.2._name": "NetworkTimeout",
        "inputparameters.parameter.2._description": "Timeout for blocking network calls (in seconds).  Use -1 for no timeout.",
        "inputparameters.parameter.2._type": "S16",
        "inputparameters.parameter.2._default": "60",
        "inputparameters.parameter.2.__prefix": "BADTOUCH",
        "inputparameters.parameter.3._name": "EnableSSL",
        "inputparameters.parameter.3._description": "Enable SSL for HTTPS targets",
        "inputparameters.parameter.3._type": "Boolean",
        "inputparameters.parameter.3._default": "false",
        "inputparameters.parameter.3.__prefix": "BADTOUCH",
        "inputparameters.parameter.4._name": "hostString",
        "inputparameters.parameter.4._description": "String to use in HTTP request",
        "inputparameters.parameter.4._type": "String",
        "inputparameters.parameter.4._default": "localhost",
        "inputparameters.parameter.4.__prefix": "BADTOUCH",
        "inputparameters.__prefix": "BADTOUCH",
        "outputparameters.parameter.0._name": "Contract",
        "outputparameters.parameter.0._description": "The contract fulfilled by this plugin",
        "outputparameters.parameter.0._type": "String",
        "outputparameters.parameter.0._value": "TouchInfo",
        "outputparameters.parameter.0.__prefix": "BADTOUCH",
        "outputparameters.parameter.1._name": "verMajor",
        "outputparameters.parameter.1._description": "IIS Major Version",
        "outputparameters.parameter.1._type": "U8",
        "outputparameters.parameter.1.__prefix": "BADTOUCH",
        "outputparameters.parameter.2._name": "verMinor",
        "outputparameters.parameter.2._description": "IIS Minor Version",
        "outputparameters.parameter.2._type": "U8",
        "outputparameters.parameter.2.__prefix": "BADTOUCH",
        "outputparameters.parameter.3._name": "OperatingSystem",
        "outputparameters.parameter.3._description": "IIS OS Version",
        "outputparameters.parameter.3._type": "String",
        "outputparameters.parameter.3.__prefix": "BADTOUCH",
        "outputparameters.parameter.4._name": "Language",
        "outputparameters.parameter.4._description": "IIS OS Language",
        "outputparameters.parameter.4._type": "String",
        "outputparameters.parameter.4.__prefix": "BADTOUCH",
        "outputparameters.parameter.5._name": "ServicePack",
        "outputparameters.parameter.5._description": "IIS OS Service Pack",
        "outputparameters.parameter.5._type": "String",
        "outputparameters.parameter.5.__prefix": "BADTOUCH",
        "outputparameters.parameter.6._name": "Path",
        "outputparameters.parameter.6._description": "IIS target pathname",
        "outputparameters.parameter.6._type": "String",
        "outputparameters.parameter.6.__prefix": "BADTOUCH",
        "outputparameters.parameter.7._name": "EnableSSL",
        "outputparameters.parameter.7._description": "Enable SSL for HTTPS targets",
        "outputparameters.parameter.7._type": "Boolean",
        "outputparameters.parameter.7.__prefix": "BADTOUCH",
        "outputparameters.parameter.8._name": "webdavFlag",
        "outputparameters.parameter.8._description": "True if webdav is enabled",
        "outputparameters.parameter.8._type": "Boolean",
        "outputparameters.parameter.8.__prefix": "BADTOUCH",
        "outputparameters.__prefix": "BADTOUCH",
        "redirection.local._protocol": "TCP",
        "redirection.local._listenaddr": "TargetIp",
        "redirection.local._listenport": "TargetPort",
        "redirection.local._destaddr": "//identifier",
        "redirection.local._destport": "//service[name='http']/port",
        "redirection.local._closeoncompletion": "true",
        "redirection.local.__prefix": "BADTOUCH",
        "redirection.__prefix": "BADTOUCH",
        "_xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
        "_xmlns:t": "tc0",
        "_id": "b9cc95073b690974e62aab9c94c2dfda94893533",
        "_name": "Iistouch",
        "_version": "1.2.2",
        "_configversion": "1.2.2.0",
        "__prefix": "BADTOUCH"
    }
]

var NAMEDPIPETOUCH = [
    {
        "inputparameters.parameter.0.default": "60",
        "inputparameters.parameter.0._name": "NetworkTimeout",
        "inputparameters.parameter.0._description": "Timeout for blocking network calls (in seconds).  Use -1 for no timeout.",
        "inputparameters.parameter.0._type": "S16",
        "inputparameters.parameter.1._name": "TargetIp",
        "inputparameters.parameter.1._description": "Target IP Address",
        "inputparameters.parameter.1._type": "IPv4",
        "inputparameters.parameter.2.default": "445",
        "inputparameters.parameter.2._name": "TargetPort",
        "inputparameters.parameter.2._description": "Port used by the SMB or NBT service",
        "inputparameters.parameter.2._type": "TcpPort",
        "inputparameters.parameter.3.value": "['\\PIPE\\browser','\\PIPE\\lsarpc','\\PIPE\\spoolss','\\PIPE\\360OnAccessGet','\\PIPE\\360OnAccessSet','\\PIPE\\aswUpdSv','\\PIPE\\afwCallbackPipe2','\\PIPE\\afwCallbackPipe2','\\PIPE\\aswUpdSv','\\PIPE\\_pspuser_780_AVGIDSMONITOR.EXE_9d97da47-8de1-4699-b3da-9eafb262f2a4','\\PIPE\\AVG7B14C58C-E30D-11DB-B553-F88A56D89593','\\PIPE\\AvgFwS8.WDCommunicationPipe1','\\PIPE\\AvgFwS8.WDCommunicationPipe2','\\PIPE\\AvgTrayPipeName000176','\\PIPE\\AvgTrayPipeName0001761','\\PIPE\\AvgTrayPipeName0001762','\\PIPE\\AvgFwS8.WDCommunicationPipe','\\PIPE\\_pspuser_3620_AVGIDSMONITOR.EXE_9fde9445-f261-4985-a056-fb033d1a64cd','\\PIPE\\AVG-CHJW-0B47172B-B945-42f8-AA88-8D4F98F660DB','\\PIPE\\AVG-CHJW-C81C2B71-E0F0-44cb-B6A7-15999D0F539A','\\PIPE\\AvgFw.WDCommunicationPipe','\\PIPE\\AvgFw.WDCommunicationPipe1','\\PIPE\\AvgFw.WDCommunicationPipe2','\\PIPE\\AvgTrayPipeName000840','\\PIPE\\AvgTrayPipeName0008401','\\PIPE\\AvgTrayPipeName0008402','\\PIPE\\AvgUIPipeName002788','\\PIPE\\AvgUIPipeName0027881','\\PIPE\\AvgUIPipeName0027882','\\PIPE\\AveSvc_EngineDienst200705311802','\\PIPE\\AveSvc_EngineService2008','\\PIPE\\avguard01','\\PIPE\\AVSCAN_REP_000000000000c883','\\PIPE\\AVWebCatServer0','\\PIPE\\AVWebGuardServer','\\PIPE\\AVWebProtServer0','\\PIPE\\SERVERPIPENAME','\\PIPE\\AveSvc_EngineService2008','\\PIPE\\bdantiphishing','\\PIPE\\bdantiphishing','\\PIPE\\bdantispam','\\PIPE\\EXTREG','\\PIPE\\LIVESRV','\\PIPE\\MIDASCOMM_SERVER','\\PIPE\\VSSERV','\\PIPE\\__fships_hook_server__','\\PIPE\\__fships_injector__','\\PIPE\\rcn_18871562230061','\\PIPE\\rcn_47843719166','\\PIPE\\rcn_49140823412','\\PIPE\\rcn_491711751329','\\PIPE\\rcn_50406860721','\\PIPE\\rcn_507341306237','\\PIPE\\rcn_51109653602','\\PIPE\\rcn_520781201855','\\PIPE\\rcn_520932065562','\\PIPE\\rcn_520932267096','\\PIPE\\rcn_522811486723','\\PIPE\\rcn_530461792332','\\PIPE\\rcn_53156781683','\\PIPE\\rcn_564531165073','\\PIPE\\rcn_580461750377','\\PIPE\\rcn_621562061643','\\PIPE\\rcn_637501693024','\\PIPE\\rcn_63750782962','\\PIPE\\rcn_647032361703','\\PIPE\\rcn_655781047893','\\PIPE\\rcn_655931694327','\\PIPE\\rcn_662811357824','\\PIPE\\rcn_67953938451','\\PIPE\\rcn_682651449794','\\PIPE\\rcn_685151921711','\\PIPE\\nai_vseconsole01','\\PIPE\\nai_vseconsole01','\\PIPE\\Symantec_{F9698F61-2E57-469B-B29B-1EFB17827356}_{0C55C096-0F1D-4F28-AAA2-85EF591126E7}','\\PIPE\\Symantec Core LC','\\PIPE\\Symantec_{586D4B8E-3DBB-4E4O-9A7E-4670F760FAC4}_{0C55C096-0F1D-4F28-AAA2-85EF591126E7}','\\PIPE\\Symantec_{EF903280-DA47-4C1B-99F8-EC15E7900956}_{0C55C096-0F1D-4F28-AAA2-85EF591126E7}','\\PIPE\\acsipc_server','\\PIPE\\pavfnlpc','\\PIPE\\Global\\PNMIPC_SH_IPT-WebProxy','\\PIPE\\pavfnlpc','\\PIPE\\PavTPU\\TPK_Event_1504','\\PIPE\\Sophos@BOPSv3','\\PIPE\\NP2970625197SRV','\\PIPE\\vmware-usbarbpipe']",
        "inputparameters.parameter.3._name": "PipeList",
        "inputparameters.parameter.3._description": "List of Pipes to check for",
        "inputparameters.parameter.3._type": "String",
        "inputparameters.parameter.3._format": "List",
        "inputparameters.parameter.3._hidden": "true",
        "inputparameters.parameter.4.value": "['OS Pipe: computer browser','OS Pipe: lsass rpc','OS Pipe: print spooler','360 Safe','360 Safe','alwil Avast professional 4.8 Avast Internet Security v5.0','Avast Internet Security 5.0','Avast Internet Security 5.0','Avast pro 4.8 or Avast IS v5.0','AVG IS 8.5','AVG IS 8.5','AVG IS 8.5','AVG IS 8.5','AVG IS 8.5','AVG IS 8.5','AVG IS 8.5','AVG IS 8.5-9.0','AVG IS 9.0.646','AVG IS 9.0.646','AVG IS 9.0.646','AVG IS 9.0.646','AVG IS 9.0.646','AVG IS 9.0.646','AVG IS 9.0.646','AVG IS 9.0.646','AVG IS 9.0.646','AVG IS 9.0.646','AVG IS 9.0.646','AVG IS 9.0.646','avira antivirus personal edition premium v7.06, avira premium security suite v7','avira premium sec suite  v8','avira premium sec suite  v8','avira premium sec suite  v8','avira premium sec suite  v8','avira premium sec suite  v8','avira premium sec suite  v8','avira premium sec suite  v8','Avira premium security suite v8','BitDefender 2010 v13','BitDefender TotalSec 2010 v13.0.11','BitDefender TotalSec 2010 v13.0.11','BitDefender TotalSec 2010 v13.0.11','BitDefender TotalSec 2010 v13.0.11 Bit Defender Total Security 2009','BitDefender TotalSec 2010 v13.0.11 Bit Defender Total Security 2009','BitDefender TotalSec 2010 v13.0.11 Bit Defender Total Security 2009','FSecure 2010','FSecure 2010','FSecure 2010','FSecure 2010','FSecure 2010','FSecure 2010','FSecure 2010','FSecure 2010','FSecure 2010','FSecure 2010','FSecure 2010','FSecure 2010','FSecure 2010','FSecure 2010','FSecure 2010','FSecure 2010','FSecure 2010','FSecure 2010','FSecure 2010','FSecure 2010','FSecure 2010','FSecure 2010','FSecure 2010','FSecure 2010','FSecure 2010','FSecure 2010','FSecure 2010','McAfee 8.7i','McAfee 8.7i','Norton Internet Security 2010','Norton IS 2008','Norton360 v4; Norton IS 2009; Norton IS 2010; Norton 360 v4','Norton360 v4','Outpost Security Suite Pro 2009 v6.5','Panda IS 2010 v15','Panda IS 2010 v15','Panda IS 2010 v15','Panda IS 2010 v15','Sophos 9.0','TrendMicro IS 2010 v17.50','VMWare Host']",
        "inputparameters.parameter.4._name": "DescList",
        "inputparameters.parameter.4._description": "List of Descriptions corresponding to pipes",
        "inputparameters.parameter.4._type": "String",
        "inputparameters.parameter.4._format": "List",
        "inputparameters.parameter.4._hidden": "true",
        "inputparameters.paramchoice.default": "SMB",
        "inputparameters.paramchoice.paramgroup.0.parameter.default": "0",
        "inputparameters.paramchoice.paramgroup.0.parameter._name": "UsingNbt",
        "inputparameters.paramchoice.paramgroup.0.parameter._description": "Boolean stating to use Nbt or not",
        "inputparameters.paramchoice.paramgroup.0.parameter._type": "Boolean",
        "inputparameters.paramchoice.paramgroup.0.parameter._hidden": "true",
        "inputparameters.paramchoice.paramgroup.0._name": "SMB",
        "inputparameters.paramchoice.paramgroup.0._description": "",
        "inputparameters.paramchoice.paramgroup.1.parameter.default": "1",
        "inputparameters.paramchoice.paramgroup.1.parameter._name": "UsingNbt",
        "inputparameters.paramchoice.paramgroup.1.parameter._description": "Boolean stating to use Nbt or not",
        "inputparameters.paramchoice.paramgroup.1.parameter._type": "Boolean",
        "inputparameters.paramchoice.paramgroup.1.parameter._hidden": "true",
        "inputparameters.paramchoice.paramgroup.1._name": "NBT",
        "inputparameters.paramchoice.paramgroup.1._description": "",
        "inputparameters.paramchoice._name": "Protocol",
        "inputparameters.paramchoice._description": "SMB (default port 445) or NBT (default port 139)",
        "redirection.local._protocol": "TCP",
        "redirection.local._listenaddr": "TargetIp",
        "redirection.local._listenport": "TargetPort",
        "redirection.local._destaddr": "TargetIp",
        "redirection.local._destport": "TargetPort",
        "redirection.local._closeoncompletion": "true",
        "redirection.remote._protocol": "TCP",
        "redirection.remote._listenaddr": "CallbackIp",
        "redirection.remote._listenport": "CallbackPort",
        "redirection.remote._destport": "CallbackLocalPort",
        "logic.service.bindtopath._name": "TargetPort",
        "logic.service.bindtopath._path": "//service[name='smtp']/port",
        "logic.service._name": "smtp",
        "logic.bindtopath._name": "TargetIp",
        "logic.bindtopath._path": "//identifier",
        "_xmlns": "urn:trch",
        "_id": "92a761c29b946aa458876ff78375e0e28bc8acb0",
        "_name": "Namedpipetouch",
        "_version": "2.0.0",
        "_configversion": "2.0.0.0",
        "_schemaversion": "2.0.0"
    }
]

var PRINTJOBDELETE = [
    {
        "inputparameters.parameter.0._name": "NetworkTimeout",
        "inputparameters.parameter.0._description": "Timeout for blocking network calls (in seconds).  Use -1 for no timeout.",
        "inputparameters.parameter.0._type": "S16",
        "inputparameters.parameter.0._default": "60",
        "inputparameters.parameter.0.__prefix": "BADTOUCH",
        "inputparameters.parameter.1._name": "TargetIp",
        "inputparameters.parameter.1._description": "Target IP Address",
        "inputparameters.parameter.1._type": "IPv4",
        "inputparameters.parameter.1._binding": "//identifier",
        "inputparameters.parameter.1.__prefix": "BADTOUCH",
        "inputparameters.parameter.2._name": "PrinterName",
        "inputparameters.parameter.2._description": "The name of the printer on target",
        "inputparameters.parameter.2._type": "UString",
        "inputparameters.parameter.2.__prefix": "BADTOUCH",
        "inputparameters.parameter.3._name": "JobId",
        "inputparameters.parameter.3._description": "The ID of the Print Job on target",
        "inputparameters.parameter.3._type": "U32",
        "inputparameters.parameter.3.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.0.paramgroup.0.parameter._name": "TargetPort",
        "inputparameters.paramchoice.0.paramgroup.0.parameter._description": "Port used by SMB",
        "inputparameters.paramchoice.0.paramgroup.0.parameter._type": "TcpPort",
        "inputparameters.paramchoice.0.paramgroup.0.parameter._default": "445",
        "inputparameters.paramchoice.0.paramgroup.0.parameter.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.0.paramgroup.0._name": "SMB",
        "inputparameters.paramchoice.0.paramgroup.0._description": "SMB over TCP",
        "inputparameters.paramchoice.0.paramgroup.0.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.0.paramgroup.1.parameter._name": "TargetPort",
        "inputparameters.paramchoice.0.paramgroup.1.parameter._description": "Port used by Netbios",
        "inputparameters.paramchoice.0.paramgroup.1.parameter._type": "TcpPort",
        "inputparameters.paramchoice.0.paramgroup.1.parameter._default": "139",
        "inputparameters.paramchoice.0.paramgroup.1.parameter.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.0.paramgroup.1._name": "NBT",
        "inputparameters.paramchoice.0.paramgroup.1._description": "Netbios over TCP",
        "inputparameters.paramchoice.0.paramgroup.1.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.0._name": "Protocol",
        "inputparameters.paramchoice.0._description": "Protocol to connect to target with",
        "inputparameters.paramchoice.0._default": "SMB",
        "inputparameters.paramchoice.0.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.0._name": "Anonymous",
        "inputparameters.paramchoice.1.paramgroup.0._description": "Anonymous (NULL session)",
        "inputparameters.paramchoice.1.paramgroup.0.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.1._name": "Guest",
        "inputparameters.paramchoice.1.paramgroup.1._description": "Guest account",
        "inputparameters.paramchoice.1.paramgroup.1.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.2.parameter._name": "Username",
        "inputparameters.paramchoice.1.paramgroup.2.parameter._description": "",
        "inputparameters.paramchoice.1.paramgroup.2.parameter._type": "UString",
        "inputparameters.paramchoice.1.paramgroup.2.parameter.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.2._name": "No password",
        "inputparameters.paramchoice.1.paramgroup.2._description": "User account with no password set",
        "inputparameters.paramchoice.1.paramgroup.2.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.3.parameter.0._name": "Username",
        "inputparameters.paramchoice.1.paramgroup.3.parameter.0._description": "",
        "inputparameters.paramchoice.1.paramgroup.3.parameter.0._type": "UString",
        "inputparameters.paramchoice.1.paramgroup.3.parameter.0.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.3.parameter.1._name": "Password",
        "inputparameters.paramchoice.1.paramgroup.3.parameter.1._description": "",
        "inputparameters.paramchoice.1.paramgroup.3.parameter.1._type": "UString",
        "inputparameters.paramchoice.1.paramgroup.3.parameter.1.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.3._name": "Password",
        "inputparameters.paramchoice.1.paramgroup.3._description": "Username and password",
        "inputparameters.paramchoice.1.paramgroup.3.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.4.parameter.0._name": "Username",
        "inputparameters.paramchoice.1.paramgroup.4.parameter.0._description": "",
        "inputparameters.paramchoice.1.paramgroup.4.parameter.0._type": "UString",
        "inputparameters.paramchoice.1.paramgroup.4.parameter.0.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.4.parameter.1._name": "NTLMHash",
        "inputparameters.paramchoice.1.paramgroup.4.parameter.1._description": "NTLM password hash (in hex)",
        "inputparameters.paramchoice.1.paramgroup.4.parameter.1._type": "UString",
        "inputparameters.paramchoice.1.paramgroup.4.parameter.1.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.4._name": "NTLM hash",
        "inputparameters.paramchoice.1.paramgroup.4._description": "Username and NTLM hash",
        "inputparameters.paramchoice.1.paramgroup.4.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.0._name": "Username",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.0._description": "",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.0._type": "UString",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.0.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.1._name": "NTLMHash",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.1._description": "NTLM password hash (in hex)",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.1._type": "UString",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.1.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.2._name": "LANMANHash",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.2._description": "LANMAN password hash (in hex)",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.2._type": "UString",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.2.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.5._name": "Both hashes",
        "inputparameters.paramchoice.1.paramgroup.5._description": "Username, NTLM hash, and LANMAN hash",
        "inputparameters.paramchoice.1.paramgroup.5.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1._name": "Credentials",
        "inputparameters.paramchoice.1._description": "Type of credentials to use",
        "inputparameters.paramchoice.1.__prefix": "BADTOUCH",
        "inputparameters.__prefix": "BADTOUCH",
        "redirection.local._protocol": "TCP",
        "redirection.local._listenaddr": "TargetIp",
        "redirection.local._listenport": "TargetPort",
        "redirection.local._destaddr": "//identifier",
        "redirection.local._destport": "//service[name='smtp']/port",
        "redirection.local._closeoncompletion": "true",
        "redirection.local.__prefix": "BADTOUCH",
        "redirection.__prefix": "BADTOUCH",
        "_xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
        "_xmlns:t": "tc0",
        "_id": "61a15b4a6a675a744bb885f4205e86a68697c8ee",
        "_name": "Printjobdelete",
        "_version": "1.0.0",
        "_configversion": "1.0.0.0",
        "__prefix": "BADTOUCH"
    }
]

var PRINTJOBLIST = [
    {
        "inputparameters.parameter.0._name": "TargetIp",
        "inputparameters.parameter.0._description": "Target IP Address",
        "inputparameters.parameter.0._type": "IPv4",
        "inputparameters.parameter.0._binding": "//identifier",
        "inputparameters.parameter.0.__prefix": "BADTOUCH",
        "inputparameters.parameter.1._name": "NetworkTimeout",
        "inputparameters.parameter.1._description": "Timeout for blocking network calls (in seconds).  Use -1 for no timeout.",
        "inputparameters.parameter.1._type": "S16",
        "inputparameters.parameter.1._default": "60",
        "inputparameters.parameter.1.__prefix": "BADTOUCH",
        "inputparameters.parameter.2._name": "PrinterName",
        "inputparameters.parameter.2._description": "The name of the printer on target",
        "inputparameters.parameter.2._type": "UString",
        "inputparameters.parameter.2.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.0.paramgroup.0.parameter._name": "TargetPort",
        "inputparameters.paramchoice.0.paramgroup.0.parameter._description": "Port used by SMB",
        "inputparameters.paramchoice.0.paramgroup.0.parameter._type": "TcpPort",
        "inputparameters.paramchoice.0.paramgroup.0.parameter._default": "445",
        "inputparameters.paramchoice.0.paramgroup.0.parameter.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.0.paramgroup.0._name": "SMB",
        "inputparameters.paramchoice.0.paramgroup.0._description": "SMB over TCP",
        "inputparameters.paramchoice.0.paramgroup.0.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.0.paramgroup.1.parameter._name": "TargetPort",
        "inputparameters.paramchoice.0.paramgroup.1.parameter._description": "Port used by Netbios",
        "inputparameters.paramchoice.0.paramgroup.1.parameter._type": "TcpPort",
        "inputparameters.paramchoice.0.paramgroup.1.parameter._default": "139",
        "inputparameters.paramchoice.0.paramgroup.1.parameter.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.0.paramgroup.1._name": "NBT",
        "inputparameters.paramchoice.0.paramgroup.1._description": "Netbios over TCP",
        "inputparameters.paramchoice.0.paramgroup.1.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.0._name": "Protocol",
        "inputparameters.paramchoice.0._description": "Protocol to connect to target with",
        "inputparameters.paramchoice.0._default": "SMB",
        "inputparameters.paramchoice.0.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.0._name": "Anonymous",
        "inputparameters.paramchoice.1.paramgroup.0._description": "Anonymous (NULL session)",
        "inputparameters.paramchoice.1.paramgroup.0.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.1._name": "Guest",
        "inputparameters.paramchoice.1.paramgroup.1._description": "Guest account",
        "inputparameters.paramchoice.1.paramgroup.1.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.2.parameter._name": "Username",
        "inputparameters.paramchoice.1.paramgroup.2.parameter._description": "",
        "inputparameters.paramchoice.1.paramgroup.2.parameter._type": "UString",
        "inputparameters.paramchoice.1.paramgroup.2.parameter.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.2._name": "No password",
        "inputparameters.paramchoice.1.paramgroup.2._description": "User account with no password set",
        "inputparameters.paramchoice.1.paramgroup.2.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.3.parameter.0._name": "Username",
        "inputparameters.paramchoice.1.paramgroup.3.parameter.0._description": "",
        "inputparameters.paramchoice.1.paramgroup.3.parameter.0._type": "UString",
        "inputparameters.paramchoice.1.paramgroup.3.parameter.0.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.3.parameter.1._name": "Password",
        "inputparameters.paramchoice.1.paramgroup.3.parameter.1._description": "",
        "inputparameters.paramchoice.1.paramgroup.3.parameter.1._type": "UString",
        "inputparameters.paramchoice.1.paramgroup.3.parameter.1.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.3._name": "Password",
        "inputparameters.paramchoice.1.paramgroup.3._description": "Username and password",
        "inputparameters.paramchoice.1.paramgroup.3.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.4.parameter.0._name": "Username",
        "inputparameters.paramchoice.1.paramgroup.4.parameter.0._description": "",
        "inputparameters.paramchoice.1.paramgroup.4.parameter.0._type": "UString",
        "inputparameters.paramchoice.1.paramgroup.4.parameter.0.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.4.parameter.1._name": "NTLMHash",
        "inputparameters.paramchoice.1.paramgroup.4.parameter.1._description": "NTLM password hash (in hex)",
        "inputparameters.paramchoice.1.paramgroup.4.parameter.1._type": "UString",
        "inputparameters.paramchoice.1.paramgroup.4.parameter.1.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.4._name": "NTLM hash",
        "inputparameters.paramchoice.1.paramgroup.4._description": "Username and NTLM hash",
        "inputparameters.paramchoice.1.paramgroup.4.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.0._name": "Username",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.0._description": "",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.0._type": "UString",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.0.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.1._name": "NTLMHash",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.1._description": "NTLM password hash (in hex)",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.1._type": "UString",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.1.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.2._name": "LANMANHash",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.2._description": "LANMAN password hash (in hex)",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.2._type": "UString",
        "inputparameters.paramchoice.1.paramgroup.5.parameter.2.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1.paramgroup.5._name": "Both hashes",
        "inputparameters.paramchoice.1.paramgroup.5._description": "Username, NTLM hash, and LANMAN hash",
        "inputparameters.paramchoice.1.paramgroup.5.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.1._name": "Credentials",
        "inputparameters.paramchoice.1._description": "Type of credentials to use",
        "inputparameters.paramchoice.1.__prefix": "BADTOUCH",
        "inputparameters.__prefix": "BADTOUCH",
        "outputparameters.parameter.0._name": "JobId",
        "outputparameters.parameter.0._description": "List of job IDs from printer",
        "outputparameters.parameter.0._type": "U32",
        "outputparameters.parameter.0._format": "List",
        "outputparameters.parameter.0.__prefix": "BADTOUCH",
        "outputparameters.parameter.1._name": "PrinterName",
        "outputparameters.parameter.1._description": "The name of the printer on target",
        "outputparameters.parameter.1._type": "UString",
        "outputparameters.parameter.1.__prefix": "BADTOUCH",
        "outputparameters.__prefix": "BADTOUCH",
        "redirection.local._protocol": "TCP",
        "redirection.local._listenaddr": "TargetIp",
        "redirection.local._listenport": "TargetPort",
        "redirection.local._destaddr": "//identifier",
        "redirection.local._destport": "//service[name='smb']/port",
        "redirection.local._closeoncompletion": "true",
        "redirection.local.__prefix": "BADTOUCH",
        "redirection.__prefix": "BADTOUCH",
        "_xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
        "_xmlns:t": "tc0",
        "_id": "561b5106574f54a157beb31c05c94a520f47ffca",
        "_name": "Printjoblist",
        "_version": "1.0.0",
        "_configversion": "1.0.0.0",
        "__prefix": "BADTOUCH"
    }
]

var RPCTOUCH = [
    {
        "inputparameters.parameter.0._name": "NetworkTimeout",
        "inputparameters.parameter.0._description": "Timeout for blocking network calls (in seconds).  Use -1 for no timeout.",
        "inputparameters.parameter.0._type": "S16",
        "inputparameters.parameter.0._default": "60",
        "inputparameters.parameter.0.__prefix": "BADTOUCH",
        "inputparameters.parameter.1._name": "TargetIp",
        "inputparameters.parameter.1._description": "Target IP Address",
        "inputparameters.parameter.1._type": "IPv4",
        "inputparameters.parameter.1._binding": "//identifier",
        "inputparameters.parameter.1.__prefix": "BADTOUCH",
        "inputparameters.parameter.2._name": "TargetPort",
        "inputparameters.parameter.2._description": "Port used by the MSRPC service. Typically 445 (SMB) or 139 (NBT)",
        "inputparameters.parameter.2._type": "TcpPort",
        "inputparameters.parameter.2._default": "445",
        "inputparameters.parameter.2._binding": "//service[name='msrpc']/port",
        "inputparameters.parameter.2.__prefix": "BADTOUCH",
        "inputparameters.parameter.3._name": "NetBIOSName",
        "inputparameters.parameter.3._type": "String",
        "inputparameters.parameter.3._description": "Name to use if running touch over NBT, Vista and above require real hostname.",
        "inputparameters.parameter.3._default": "*SMBSERVER",
        "inputparameters.parameter.3.__prefix": "BADTOUCH",
        "inputparameters.parameter.4._name": "TouchLanguage",
        "inputparameters.parameter.4._type": "Boolean",
        "inputparameters.parameter.4._description": "Run language touch against RPC spooler service.",
        "inputparameters.parameter.4._default": "False",
        "inputparameters.parameter.4.__prefix": "BADTOUCH",
        "inputparameters.parameter.5._name": "TouchArchitecture",
        "inputparameters.parameter.5._type": "Boolean",
        "inputparameters.parameter.5._description": "Run architecture touch against SMB via a memory disclosure bug.",
        "inputparameters.parameter.5._default": "False",
        "inputparameters.parameter.5.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.paramgroup.0._name": "SMB",
        "inputparameters.paramchoice.paramgroup.0._description": "SMB over TCP",
        "inputparameters.paramchoice.paramgroup.0.__prefix": "BADTOUCH",
        "inputparameters.paramchoice.paramgroup.1._name": "NBT",
        "inputparameters.paramchoice.paramgroup.1._description": "Netbios over TCP",
        "inputparameters.paramchoice.paramgroup.1.__prefix": "BADTOUCH",
        "inputparameters.paramchoice._name": "Protocol",
        "inputparameters.paramchoice._description": "Protocol to connect to target with. Touches will vary with protocol.",
        "inputparameters.paramchoice._default": "SMB",
        "inputparameters.paramchoice.__prefix": "BADTOUCH",
        "inputparameters.__prefix": "BADTOUCH",
        "outputparameters.parameter.0._name": "Protocol",
        "outputparameters.parameter.0._type": "String",
        "outputparameters.parameter.0._description": "",
        "outputparameters.parameter.0.__prefix": "BADTOUCH",
        "outputparameters.parameter.1._name": "Target",
        "outputparameters.parameter.1._type": "String",
        "outputparameters.parameter.1._description": "",
        "outputparameters.parameter.1.__prefix": "BADTOUCH",
        "outputparameters.parameter.2._name": "TargetString",
        "outputparameters.parameter.2._type": "String",
        "outputparameters.parameter.2._description": "",
        "outputparameters.parameter.2.__prefix": "BADTOUCH",
        "outputparameters.parameter.3._name": "TargetDWORD",
        "outputparameters.parameter.3._type": "U32",
        "outputparameters.parameter.3._description": "",
        "outputparameters.parameter.3.__prefix": "BADTOUCH",
        "outputparameters.parameter.4._name": "Language",
        "outputparameters.parameter.4._type": "String",
        "outputparameters.parameter.4._description": "",
        "outputparameters.parameter.4.__prefix": "BADTOUCH",
        "outputparameters.parameter.5._name": "NetworkTimeout",
        "outputparameters.parameter.5._type": "S16",
        "outputparameters.parameter.5._description": "",
        "outputparameters.parameter.5.__prefix": "BADTOUCH",
        "outputparameters.parameter.6._name": "Contract",
        "outputparameters.parameter.6._description": "The contract fulfilled by this plugin",
        "outputparameters.parameter.6._type": "String",
        "outputparameters.parameter.6._value": "StagedUpload",
        "outputparameters.parameter.6.__prefix": "BADTOUCH",
        "outputparameters.__prefix": "BADTOUCH",
        "redirection.local._protocol": "TCP",
        "redirection.local._listenaddr": "TargetIp",
        "redirection.local._listenport": "TargetPort",
        "redirection.local._destaddr": "//identifier",
        "redirection.local._destport": "//service[name='msrpc']/port",
        "redirection.local._closeoncompletion": "true",
        "redirection.local.__prefix": "BADTOUCH",
        "redirection.__prefix": "BADTOUCH",
        "_xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
        "_xmlns:t": "tc0",
        "_id": "cbe9b627fe881b0f5fe6122af36fe6234935c7e7",
        "_name": "Rpctouch",
        "_version": "2.1.0",
        "_configversion": "2.1.0.0",
        "__prefix": "BADTOUCH"
    }
]

var SMBTOUCH = [
    {
        "inputparameters.parameter.0.default": "60",
        "inputparameters.parameter.0._type": "S16",
        "inputparameters.parameter.0._name": "NetworkTimeout",
        "inputparameters.parameter.0._description": "Timeout for blocking network calls (in seconds).  Use -1 for no timeout.",
        "inputparameters.parameter.1._type": "IPv4",
        "inputparameters.parameter.1._name": "TargetIp",
        "inputparameters.parameter.1._description": "Target IP Address",
        "inputparameters.parameter.2.default": "445",
        "inputparameters.parameter.2._type": "TcpPort",
        "inputparameters.parameter.2._name": "TargetPort",
        "inputparameters.parameter.2._description": "Port used by the SMB service",
        "inputparameters.parameter.3._hidden": "true",
        "inputparameters.parameter.3._required": "false",
        "inputparameters.parameter.3._type": "IPv4",
        "inputparameters.parameter.3._name": "RedirectedTargetIp",
        "inputparameters.parameter.3._description": "Physical (redirected) target IP",
        "inputparameters.parameter.4._hidden": "true",
        "inputparameters.parameter.4._required": "false",
        "inputparameters.parameter.4._type": "TcpPort",
        "inputparameters.parameter.4._name": "RedirectedTargetPort",
        "inputparameters.parameter.4._description": "Physical (redirected) target port",
        "inputparameters.parameter.5.default": "",
        "inputparameters.parameter.5._type": "String",
        "inputparameters.parameter.5._name": "Pipe",
        "inputparameters.parameter.5._description": "Test an additional pipe to see if it is accessible (optional)",
        "inputparameters.parameter.6.default": "",
        "inputparameters.parameter.6._type": "Buffer",
        "inputparameters.parameter.6._name": "Share",
        "inputparameters.parameter.6._description": "Test a file share to see if it is accessible (optional), entered as hex bytes (in unicode)",
        "inputparameters.paramchoice.0.default": "SMB",
        "inputparameters.paramchoice.0.paramgroup.0.parameter.default": "0",
        "inputparameters.paramchoice.0.paramgroup.0.parameter._hidden": "true",
        "inputparameters.paramchoice.0.paramgroup.0.parameter._type": "Boolean",
        "inputparameters.paramchoice.0.paramgroup.0.parameter._name": "UsingNbt",
        "inputparameters.paramchoice.0.paramgroup.0.parameter._description": "Boolean stating to use Nbt or not",
        "inputparameters.paramchoice.0.paramgroup.0._name": "SMB",
        "inputparameters.paramchoice.0.paramgroup.0._description": "",
        "inputparameters.paramchoice.0.paramgroup.1.parameter.default": "1",
        "inputparameters.paramchoice.0.paramgroup.1.parameter._hidden": "true",
        "inputparameters.paramchoice.0.paramgroup.1.parameter._type": "Boolean",
        "inputparameters.paramchoice.0.paramgroup.1.parameter._name": "UsingNbt",
        "inputparameters.paramchoice.0.paramgroup.1.parameter._description": "Boolean stating to use Nbt or not",
        "inputparameters.paramchoice.0.paramgroup.1._name": "NBT",
        "inputparameters.paramchoice.0.paramgroup.1._description": "",
        "inputparameters.paramchoice.0._name": "Protocol",
        "inputparameters.paramchoice.0._description": "SMB (default port 445) or NBT (default port 139)",
        "inputparameters.paramchoice.1.default": "Anonymous",
        "inputparameters.paramchoice.1.paramgroup.0._name": "Anonymous",
        "inputparameters.paramchoice.1.paramgroup.0._description": "Anonymous (NULL session)",
        "inputparameters.paramchoice.1.paramgroup.1._name": "Guest",
        "inputparameters.paramchoice.1.paramgroup.1._description": "Guest account",
        "inputparameters.paramchoice.1.paramgroup.2.parameter._type": "Buffer",
        "inputparameters.paramchoice.1.paramgroup.2.parameter._name": "Username",
        "inputparameters.paramchoice.1.paramgroup.2.parameter._description": "Username entered as hex bytes (in unicode)",
        "inputparameters.paramchoice.1.paramgroup.2._name": "Blank",
        "inputparameters.paramchoice.1.paramgroup.2._description": "User account with no password set",
        "inputparameters.paramchoice.1.paramgroup.3.parameter.0._type": "Buffer",
        "inputparameters.paramchoice.1.paramgroup.3.parameter.0._name": "Username",
        "inputparameters.paramchoice.1.paramgroup.3.parameter.0._description": "Username entered as hex bytes (in unicode)",
        "inputparameters.paramchoice.1.paramgroup.3.parameter.1._type": "Buffer",
        "inputparameters.paramchoice.1.paramgroup.3.parameter.1._name": "Password",
        "inputparameters.paramchoice.1.paramgroup.3.parameter.1._description": "Password entered as hex bytes (in unicode)",
        "inputparameters.paramchoice.1.paramgroup.3._name": "Password",
        "inputparameters.paramchoice.1.paramgroup.3._description": "User name and password",
        "inputparameters.paramchoice.1.paramgroup.4.parameter.0._type": "Buffer",
        "inputparameters.paramchoice.1.paramgroup.4.parameter.0._name": "Username",
        "inputparameters.paramchoice.1.paramgroup.4.parameter.0._description": "Username entered as hex bytes (in unicode)",
        "inputparameters.paramchoice.1.paramgroup.4.parameter.1._type": "Buffer",
        "inputparameters.paramchoice.1.paramgroup.4.parameter.1._name": "NtlmHash",
        "inputparameters.paramchoice.1.paramgroup.4.parameter.1._description": "NTLM password hash (in hex)",
        "inputparameters.paramchoice.1.paramgroup.4._name": "NTLM",
        "inputparameters.paramchoice.1.paramgroup.4._description": "User name and NTLM hash",
        "inputparameters.paramchoice.1._name": "Credentials",
        "inputparameters.paramchoice.1._description": "Type of credentials to use",
        "constants.parameter.0.value": "0",
        "constants.parameter.0._type": "U8",
        "constants.parameter.0._name": "Anonymous",
        "constants.parameter.0._description": "",
        "constants.parameter.1.value": "1",
        "constants.parameter.1._type": "U8",
        "constants.parameter.1._name": "Guest",
        "constants.parameter.1._description": "",
        "constants.parameter.2.value": "2",
        "constants.parameter.2._type": "U8",
        "constants.parameter.2._name": "Blank",
        "constants.parameter.2._description": "",
        "constants.parameter.3.value": "3",
        "constants.parameter.3._type": "U8",
        "constants.parameter.3._name": "Password",
        "constants.parameter.3._description": "",
        "constants.parameter.4.value": "4",
        "constants.parameter.4._type": "U8",
        "constants.parameter.4._name": "NTLM",
        "constants.parameter.4._description": "",
        "outputparameters.parameter.0._type": "String",
        "outputparameters.parameter.0._name": "Target",
        "outputparameters.parameter.0._description": "Operating System, Service Pack, of Target OS",
        "outputparameters.parameter.1._type": "String",
        "outputparameters.parameter.1._name": "TargetOsArchitecture",
        "outputparameters.parameter.1._description": "Target architecture",
        "outputparameters.parameter.2._type": "String",
        "outputparameters.parameter.2._name": "PipeName",
        "outputparameters.parameter.2._description": "Pipe available to use",
        "outputparameters.parameter.3._type": "Buffer",
        "outputparameters.parameter.3._name": "ShareName",
        "outputparameters.parameter.3._description": "Share available to use",
        "outputparameters.parameter.4._type": "String",
        "outputparameters.parameter.4._name": "Protocol",
        "outputparameters.parameter.4._description": "SMB or NBT",
        "outputparameters.parameter.5._type": "String",
        "outputparameters.parameter.5._name": "Credentials",
        "outputparameters.parameter.5._description": "The architecture of the target operating system",
        "outputparameters.parameter.6._type": "Buffer",
        "outputparameters.parameter.6._name": "Username",
        "outputparameters.parameter.6._description": "Username entered as hex bytes (in unicode)",
        "outputparameters.parameter.7._type": "Buffer",
        "outputparameters.parameter.7._name": "Password",
        "outputparameters.parameter.7._description": "Password entered as hex bytes (in unicode)",
        "outputparameters.parameter.8._type": "Buffer",
        "outputparameters.parameter.8._name": "NtlmHash",
        "outputparameters.parameter.8._description": "NTLM password hash (in hex)",
        "errors.errorcode.0._name": "SMBT_SUCCESS",
        "errors.errorcode.0._value": "EDF_SUCCESS",
        "errors.errorcode.0._description": "Smbtouch executed successfully.",
        "errors.errorcode.1._name": "SMBT_RESULT_NETWORK_ERROR",
        "errors.errorcode.1._value": "65",
        "errors.errorcode.1._description": "A network error occured",
        "errors.errorcode.2._name": "SMBT_RESULT_UNSUPPORTED_OS",
        "errors.errorcode.2._value": "66",
        "errors.errorcode.2._description": "The target OS is not recognized or supported",
        "errors.errorcode.3._name": "SMBT_RESULT_INVALID_PARAM",
        "errors.errorcode.3._value": "67",
        "errors.errorcode.3._description": "A parameter is invalid",
        "redirection.local._protocol": "TCP",
        "redirection.local._listenaddr": "RedirectedTargetIp",
        "redirection.local._listenport": "RedirectedTargetPort",
        "redirection.local._closeoncompletion": "true",
        "redirection.local._destaddr": "TargetIp",
        "redirection.local._destport": "TargetPort",
        "_xmlns": "urn:trch",
        "_name": "Smbtouch",
        "_version": "1.1.1",
        "_schemaversion": "2.1.0",
        "_configversion": "1.1.1.0",
        "_id": "985f383e6edd6d9397aa5da9601c8bc867f6b713"
    }
]

var WEBADMINTOUCH = [
    {
        "inputparameters.parameter.0._name": "NetworkTimeout",
        "inputparameters.parameter.0._description": "Timeout for blocking network calls (in seconds).  Use 0 for no timeout.",
        "inputparameters.parameter.0._type": "S16",
        "inputparameters.parameter.0._default": "60",
        "inputparameters.parameter.0.__prefix": "BADTOUCH",
        "inputparameters.parameter.1._name": "TargetIp",
        "inputparameters.parameter.1._description": "Target IPv4 Address (dot notation)",
        "inputparameters.parameter.1._type": "IPv4",
        "inputparameters.parameter.1._binding": "//identifier",
        "inputparameters.parameter.1.__prefix": "BADTOUCH",
        "inputparameters.parameter.2._name": "TargetPort",
        "inputparameters.parameter.2._description": "Target Port Number",
        "inputparameters.parameter.2._type": "TcpPort",
        "inputparameters.parameter.2._binding": "//service[name='http']/port",
        "inputparameters.parameter.2.__prefix": "BADTOUCH",
        "inputparameters.parameter.3._name": "ExpectedProtocol",
        "inputparameters.parameter.3._description": "WebAdmin protocol (http, https)",
        "inputparameters.parameter.3._type": "String",
        "inputparameters.parameter.3.__prefix": "BADTOUCH",
        "inputparameters.parameter.4._name": "ExpectedDomain",
        "inputparameters.parameter.4._description": "WebAdmin IPv4 Address (dot notation)",
        "inputparameters.parameter.4._type": "IPv4",
        "inputparameters.parameter.4._binding": "//identifier",
        "inputparameters.parameter.4.__prefix": "BADTOUCH",
        "inputparameters.parameter.5._name": "ExpectedPort",
        "inputparameters.parameter.5._description": "WebAdmin Port Number",
        "inputparameters.parameter.5._type": "TcpPort",
        "inputparameters.parameter.5._binding": "//service[name='http']/port",
        "inputparameters.parameter.5.__prefix": "BADTOUCH",
        "inputparameters.parameter.6._name": "TargetAcctDomain",
        "inputparameters.parameter.6._description": "Target email domain",
        "inputparameters.parameter.6._type": "String",
        "inputparameters.parameter.6.__prefix": "BADTOUCH",
        "inputparameters.parameter.7._name": "TargetAcctUsr",
        "inputparameters.parameter.7._description": "Target account username",
        "inputparameters.parameter.7._type": "String",
        "inputparameters.parameter.7.__prefix": "BADTOUCH",
        "inputparameters.parameter.8._name": "TargetAcctPwd",
        "inputparameters.parameter.8._description": "Target account password",
        "inputparameters.parameter.8._type": "String",
        "inputparameters.parameter.8.__prefix": "BADTOUCH",
        "inputparameters.parameter.9._name": "SupportedVersions",
        "inputparameters.parameter.9._description": "List of strings of supported version numbers",
        "inputparameters.parameter.9._type": "String",
        "inputparameters.parameter.9._format": "List",
        "inputparameters.parameter.9._hidden": "true",
        "inputparameters.parameter.9._value": "['3.3.0',                          '3.4.00',                          '3.4.10',                          '3.4.20',                          '3.4.3',                         '10.0.0',                         '10.0.1',                         '10.0.2',                         '10.0.3',                          '10.0.4',                         '10.0.5',                         '10.1.0',                         '10.1.1',                         '10.1.2']",
        "inputparameters.parameter.9.__prefix": "BADTOUCH",
        "inputparameters.__prefix": "BADTOUCH",
        "redirection.local._protocol": "TCP",
        "redirection.local._listenaddr": "TargetIp",
        "redirection.local._listenport": "TargetPort",
        "redirection.local._destaddr": "//identifier",
        "redirection.local._destport": "//service[name='smtp']/port",
        "redirection.local._closeoncompletion": "true",
        "redirection.local.__prefix": "BADTOUCH",
        "redirection.remote._protocol": "TCP",
        "redirection.remote._listenaddr": "CallbackIp",
        "redirection.remote._listenport": "CallbackPort",
        "redirection.remote._destport": "CallbackLocalPort",
        "redirection.remote.__prefix": "BADTOUCH",
        "redirection.__prefix": "BADTOUCH",
        "_xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
        "_xmlns:t": "tc0",
        "_id": "f8f36381b1933b8ae3f8a7dd945f913d1afd7e0c",
        "_name": "Webadmintouch",
        "_version": "1.0.1",
        "_configversion": "1.0.1.0",
        "__prefix": "BADTOUCH"
    }
]

var WORLDCLIENTTOUCH = [
    {
        "inputparameters.parameter.0._name": "NetworkTimeout",
        "inputparameters.parameter.0._description": "Timeout for blocking network calls (in seconds).  Use 0 for no timeout.",
        "inputparameters.parameter.0._type": "S16",
        "inputparameters.parameter.0._default": "60",
        "inputparameters.parameter.0.__prefix": "BADTOUCH",
        "inputparameters.parameter.1._name": "TargetIp",
        "inputparameters.parameter.1._description": "Target IPv4 Address (dot notation)",
        "inputparameters.parameter.1._type": "IPv4",
        "inputparameters.parameter.1._binding": "//identifier",
        "inputparameters.parameter.1.__prefix": "BADTOUCH",
        "inputparameters.parameter.2._name": "TargetPort",
        "inputparameters.parameter.2._description": "Target Port Number",
        "inputparameters.parameter.2._type": "TcpPort",
        "inputparameters.parameter.2._binding": "//service[name='http']/port",
        "inputparameters.parameter.2.__prefix": "BADTOUCH",
        "inputparameters.parameter.3._name": "ExpectedProtocol",
        "inputparameters.parameter.3._description": "WorldClient protocol (http, https)",
        "inputparameters.parameter.3._type": "String",
        "inputparameters.parameter.3.__prefix": "BADTOUCH",
        "inputparameters.parameter.4._name": "ExpectedDomain",
        "inputparameters.parameter.4._description": "WorldClient IPv4 Address (dot notation)",
        "inputparameters.parameter.4._type": "IPv4",
        "inputparameters.parameter.4._binding": "//identifier",
        "inputparameters.parameter.4.__prefix": "BADTOUCH",
        "inputparameters.parameter.5._name": "ExpectedPort",
        "inputparameters.parameter.5._description": "WorldClient Port Number",
        "inputparameters.parameter.5._type": "TcpPort",
        "inputparameters.parameter.5._binding": "//service[name='http']/port",
        "inputparameters.parameter.5.__prefix": "BADTOUCH",
        "inputparameters.parameter.6._name": "TargetAcctDomain",
        "inputparameters.parameter.6._description": "Target account email domain",
        "inputparameters.parameter.6._type": "String",
        "inputparameters.parameter.6.__prefix": "BADTOUCH",
        "inputparameters.parameter.7._name": "TargetAcctUsr",
        "inputparameters.parameter.7._description": "Target account username",
        "inputparameters.parameter.7._type": "String",
        "inputparameters.parameter.7.__prefix": "BADTOUCH",
        "inputparameters.parameter.8._name": "TargetAcctPwd",
        "inputparameters.parameter.8._description": "Target account password",
        "inputparameters.parameter.8._type": "String",
        "inputparameters.parameter.8.__prefix": "BADTOUCH",
        "inputparameters.parameter.9._name": "SupportedVersions",
        "inputparameters.parameter.9._description": "List of strings of supported WorldClient version numbers",
        "inputparameters.parameter.9._type": "String",
        "inputparameters.parameter.9._format": "List",
        "inputparameters.parameter.9._hidden": "true",
        "inputparameters.parameter.9._value": "['9.5.2',                          '9.6.0',                          '9.6.1',                          '9.6.2',                          '9.6.3',                          '9.6.4',                          '9.6.5',                          '9.6.6',                         '10.0.0',                         '10.0.1',                         '10.0.2',                         '10.0.3',                         '10.0.4',                         '10.0.5',                         '10.1.0',                         '10.1.1',                         '10.1.2']",
        "inputparameters.parameter.9.__prefix": "BADTOUCH",
        "inputparameters.parameter.10._name": "ServerHeaderVersions",
        "inputparameters.parameter.10._description": "List of strings of WorldClient versions which respond with the Server header",
        "inputparameters.parameter.10._type": "String",
        "inputparameters.parameter.10._format": "List",
        "inputparameters.parameter.10._hidden": "true",
        "inputparameters.parameter.10._value": "['9.5.2',                          '9.6.0',                          '9.6.1',                          '9.6.2',                          '9.6.3',                          '9.6.4',                          '9.6.5',                          '9.6.6',                         '10.0.0',                         '10.0.1',                         '10.0.2',                         '10.0.3',                         '10.0.4',                         '10.0.5']",
        "inputparameters.parameter.10.__prefix": "BADTOUCH",
        "inputparameters.parameter.11._name": "PossiblyLimitedVersions",
        "inputparameters.parameter.11._description": "List of strings of WorldClient versions with the limited free option",
        "inputparameters.parameter.11._type": "String",
        "inputparameters.parameter.11._format": "List",
        "inputparameters.parameter.11._hidden": "true",
        "inputparameters.parameter.11._value": "['10.0.0',                          '10.0.1',                          '10.0.2',                          '10.0.3',                          '10.0.4',                          '10.0.5',                          '10.1.0',                          '10.1.1',                          '10.1.2']",
        "inputparameters.parameter.11.__prefix": "BADTOUCH",
        "inputparameters.__prefix": "BADTOUCH",
        "redirection.local._protocol": "TCP",
        "redirection.local._listenaddr": "TargetIp",
        "redirection.local._listenport": "TargetPort",
        "redirection.local._destaddr": "//identifier",
        "redirection.local._destport": "//service[name='http']/port",
        "redirection.local._closeoncompletion": "true",
        "redirection.local.__prefix": "BADTOUCH",
        "redirection.remote._protocol": "TCP",
        "redirection.remote._listenaddr": "CallbackIp",
        "redirection.remote._listenport": "CallbackPort",
        "redirection.remote._destport": "CallbackLocalPort",
        "redirection.remote.__prefix": "BADTOUCH",
        "redirection.__prefix": "BADTOUCH",
        "_xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
        "_xmlns:t": "tc0",
        "_id": "b0cec9189bbf3c41c3991a08a1f96b68b5ed0127",
        "_name": "Worldclienttouch",
        "_version": "1.0.1",
        "_configversion": "1.0.1.0",
        "__prefix": "BADTOUCH"
    }
]

var OPS = [ ARCHITOUCH,
            DOMAINTOUCH,
            ECLIPSEDWINGTOUCH,
            EDUCATEDSCHOLARTOUCH,
            EMERALDTHREADTOUCH,
            ERRATICGOPHERTOUCH,
            ESTEEMAUDITTOUCH,
            EXPLODINGCANTOUCH,
            IISTOUCH,
            NAMEDPIPETOUCH,
            PRINTJOBDELETE,
            PRINTJOBLIST,
            RPCTOUCH
            SMBTOUCH,
            WEBADMINTOUCH,
            WORLDCLIENTTOUCH
    ]

print(OPS);


//]]>
</script>